//protobuf file syntax

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/bloom.proto

// package name for the protobuf file

package bloom_pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterType    string                 `protobuf:"bytes,1,opt,name=filter_type,json=filterType,proto3" json:"filter_type,omitempty"`
	ExpectedItems int32                  `protobuf:"varint,2,opt,name=expected_items,json=expectedItems,proto3" json:"expected_items,omitempty"`
	FalsePosRate  float64                `protobuf:"fixed64,3,opt,name=false_pos_rate,json=falsePosRate,proto3" json:"false_pos_rate,omitempty"`
	// optional
	GrowthFactor  float64 `protobuf:"fixed64,4,opt,name=growth_factor,json=growthFactor,proto3" json:"growth_factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFilterRequest) Reset() {
	*x = CreateFilterRequest{}
	mi := &file_api_proto_bloom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFilterRequest) ProtoMessage() {}

func (x *CreateFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bloom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFilterRequest.ProtoReflect.Descriptor instead.
func (*CreateFilterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bloom_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFilterRequest) GetFilterType() string {
	if x != nil {
		return x.FilterType
	}
	return ""
}

func (x *CreateFilterRequest) GetExpectedItems() int32 {
	if x != nil {
		return x.ExpectedItems
	}
	return 0
}

func (x *CreateFilterRequest) GetFalsePosRate() float64 {
	if x != nil {
		return x.FalsePosRate
	}
	return 0
}

func (x *CreateFilterRequest) GetGrowthFactor() float64 {
	if x != nil {
		return x.GrowthFactor
	}
	return 0
}

type CreateFilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFilterResponse) Reset() {
	*x = CreateFilterResponse{}
	mi := &file_api_proto_bloom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFilterResponse) ProtoMessage() {}

func (x *CreateFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bloom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFilterResponse.ProtoReflect.Descriptor instead.
func (*CreateFilterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bloom_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFilterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateFilterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_api_proto_bloom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bloom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bloom_proto_rawDescGZIP(), []int{2}
}

func (x *AddRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_api_proto_bloom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bloom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bloom_proto_rawDescGZIP(), []int{3}
}

func (x *AddResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_api_proto_bloom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bloom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bloom_proto_rawDescGZIP(), []int{4}
}

func (x *CheckRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_api_proto_bloom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bloom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bloom_proto_rawDescGZIP(), []int{5}
}

func (x *CheckResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_api_proto_bloom_proto protoreflect.FileDescriptor

const file_api_proto_bloom_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/bloom.proto\x12\x05bloom\x1a\x1cgoogle/api/annotations.proto\"\xa8\x01\n" +
	"\x13CreateFilterRequest\x12\x1f\n" +
	"\vfilter_type\x18\x01 \x01(\tR\n" +
	"filterType\x12%\n" +
	"\x0eexpected_items\x18\x02 \x01(\x05R\rexpectedItems\x12$\n" +
	"\x0efalse_pos_rate\x18\x03 \x01(\x01R\ffalsePosRate\x12#\n" +
	"\rgrowth_factor\x18\x04 \x01(\x01R\fgrowthFactor\"J\n" +
	"\x14CreateFilterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\" \n" +
	"\n" +
	"AddRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"'\n" +
	"\vAddResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\"\n" +
	"\fCheckRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"%\n" +
	"\rCheckResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found2\x88\x02\n" +
	"\fBloomService\x12^\n" +
	"\fCreateFilter\x12\x1a.bloom.CreateFilterRequest\x1a\x1b.bloom.CreateFilterResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/filter\x12G\n" +
	"\x03Add\x12\x11.bloom.AddRequest\x1a\x12.bloom.AddResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/filter/add\x12O\n" +
	"\x05Check\x12\x13.bloom.CheckRequest\x1a\x14.bloom.CheckResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/filter/checkB\x17Z\x15bloombox/api/bloom_pbb\x06proto3"

var (
	file_api_proto_bloom_proto_rawDescOnce sync.Once
	file_api_proto_bloom_proto_rawDescData []byte
)

func file_api_proto_bloom_proto_rawDescGZIP() []byte {
	file_api_proto_bloom_proto_rawDescOnce.Do(func() {
		file_api_proto_bloom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_bloom_proto_rawDesc), len(file_api_proto_bloom_proto_rawDesc)))
	})
	return file_api_proto_bloom_proto_rawDescData
}

var file_api_proto_bloom_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_bloom_proto_goTypes = []any{
	(*CreateFilterRequest)(nil),  // 0: bloom.CreateFilterRequest
	(*CreateFilterResponse)(nil), // 1: bloom.CreateFilterResponse
	(*AddRequest)(nil),           // 2: bloom.AddRequest
	(*AddResponse)(nil),          // 3: bloom.AddResponse
	(*CheckRequest)(nil),         // 4: bloom.CheckRequest
	(*CheckResponse)(nil),        // 5: bloom.CheckResponse
}
var file_api_proto_bloom_proto_depIdxs = []int32{
	0, // 0: bloom.BloomService.CreateFilter:input_type -> bloom.CreateFilterRequest
	2, // 1: bloom.BloomService.Add:input_type -> bloom.AddRequest
	4, // 2: bloom.BloomService.Check:input_type -> bloom.CheckRequest
	1, // 3: bloom.BloomService.CreateFilter:output_type -> bloom.CreateFilterResponse
	3, // 4: bloom.BloomService.Add:output_type -> bloom.AddResponse
	5, // 5: bloom.BloomService.Check:output_type -> bloom.CheckResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_bloom_proto_init() }
func file_api_proto_bloom_proto_init() {
	if File_api_proto_bloom_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_bloom_proto_rawDesc), len(file_api_proto_bloom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_bloom_proto_goTypes,
		DependencyIndexes: file_api_proto_bloom_proto_depIdxs,
		MessageInfos:      file_api_proto_bloom_proto_msgTypes,
	}.Build()
	File_api_proto_bloom_proto = out.File
	file_api_proto_bloom_proto_goTypes = nil
	file_api_proto_bloom_proto_depIdxs = nil
}
